### ISSUE TITLE
Plugin not responding

### ISSUE THREAD

**Issue by matthewjt** [kolsys/YouTubeTV.bundle#63]
I updated the plugin to the latest version, cleared cache and re-authorized.  I see all my playlists and videos but no video will play (on multiple clients).  I just see 500 messages coming back.  Can I get you more information?

Jan 10, 2019 19:14:19.136 [0x14bb76dfe700] DEBUG - Plug-in com.plexapp.plugins.youtube.tv has been used 50 times.
Jan 10, 2019 19:14:19.136 [0x14bb76dfe700] DEBUG - [com.plexapp.plugins.youtube.tv] Sending command over HTTP (GET): /video/youtubetv/video/view?vid=y04xG7qCEh0
Jan 10, 2019 19:14:19.136 [0x14bb76dfe700] DEBUG - HTTP requesting GET http://127.0.0.1:33251/video/youtubetv/video/view?vid=y04xG7qCEh0
Jan 10, 2019 19:14:20.028 [0x14bb76dfe700] DEBUG - HTTP 500 response from GET http://127.0.0.1:33251/video/youtubetv/video/view?vid=y04xG7qCEh0
Jan 10, 2019 19:14:20.029 [0x14bb76dfe700] DEBUG - [com.plexapp.plugins.youtube.tv] HTTP reply status 500, with 111 bytes of content.
Jan 10, 2019 19:14:20.031 [0x14bb7f1fe700] DEBUG - Completed: [10.223.223.211:52069] 500 GET /video/youtubetv/video/view?vid=y04xG7qCEh0 (15 live) TLS GZIP 897ms 643 bytes (pipelined: 8)

**Comment by SteveWilliams58** [comment]
Yep I have the same problem again tried going back to 4.9 to no avail I get the plugin not responding issue on rasplex and in the browser (firefox)

**Comment by supwner** [comment]
Same problem. Media server running on Windows 10, Installed Reinstalled both media server and youtube plugin.

[com.plexapp.plugins.youtube.tv.log](https://github.com/kolsys/YouTubeTV.bundle/files/2753342/com.plexapp.plugins.youtube.tv.log)

**Comment by kolsys** [comment]
Fixed in v4.12 #65

**Comment by matthewjt** [comment]
Just tried the latest and I still get plugin not responding.

Jan 14, 2019 21:01:53.255 [0x1473243fb700] DEBUG - Plug-in com.plexapp.plugins.youtube.tv has been used 21 times.
Jan 14, 2019 21:01:53.264 [0x1473243fb700] DEBUG - [com.plexapp.plugins.youtube.tv] Sending command over HTTP (GET): /video/youtubetv/video/view?vid=KzTTF_WNTfM
Jan 14, 2019 21:01:53.265 [0x1473243fb700] DEBUG - HTTP requesting GET http://127.0.0.1:33255/video/youtubetv/video/view?vid=KzTTF_WNTfM
Jan 14, 2019 21:01:53.345 [0x1473243fb700] DEBUG - HTTP 500 response from GET http://127.0.0.1:33255/video/youtubetv/video/view?vid=KzTTF_WNTfM
Jan 14, 2019 21:01:53.345 [0x1473243fb700] DEBUG - [com.plexapp.plugins.youtube.tv] HTTP reply status 500, with 111 bytes of content.
Jan 14, 2019 21:01:53.352 [0x14732e1fe700] DEBUG - Completed: [10.223.223.211:50110] 500 GET /video/youtubetv/video/view?vid=KzTTF_WNTfM (10 live) TLS GZIP 101ms 643 bytes (pipelined: 1)

**Comment by kolsys** [comment]
@matthewjt Can you show error in com.plexapp.plugins.youtube.tv.log or com.plexapp.system.log?

**Comment by matthewjt** [comment]
@kolsys Sorry, I'm an idiot.  I started combing through the youtube.tv.log and kept seeing the 500 error 'this video is not available'.  Turns out those videos I added to my playlists are...unavailable!  I found a few that were still available and they played fine.  Thanks!

**Comment by matthewjt** [comment]
Well, one worked, now none work.  Not sure what the issue is.  I cleared the cache and re-installed the app with the same results.
[com.plexapp.plugins.youtube.tv.log](https://github.com/kolsys/YouTubeTV.bundle/files/2763823/com.plexapp.plugins.youtube.tv.log)

**Comment by SteveWilliams58** [comment]
Just to say mine working now muchos gracias good buddy :)

**Comment by matthewjt** [comment]
Not sure why, but the videos that didn't work started working. Maybe it has something to do with ads? The videos I tried are working.
